from pathlib import Path

p = Path('tests/jingle/bundlesignaling.cpp')
s = p.read_text()

old_helper = '''static void rejectJingleTask(RootTaskKeeper &keeper, const Jid &peer)\n{\n    auto pending = keeper.task();\n    check(pending, "content-accept did not create a retained Jingle IQ task");\n\n    QDomDocument replyDoc;\n    auto reply = replyDoc.createElement(QStringLiteral("iq"));\n    replyDoc.appendChild(reply);\n    reply.setAttribute(QStringLiteral("type"), QStringLiteral("error"));\n    reply.setAttribute(QStringLiteral("from"), peer.full());\n    reply.setAttribute(QStringLiteral("id"), pending->id());\n    auto error = replyDoc.createElement(QStringLiteral("error"));\n    error.setAttribute(QStringLiteral("type"), QStringLiteral("cancel"));\n    error.appendChild(replyDoc.createElementNS(QStringLiteral("urn:ietf:params:xml:ns:xmpp-stanzas"),\n                                               QStringLiteral("service-unavailable")));\n    reply.appendChild(error);\n    check(pending->take(reply), "content-accept IQ error was not consumed");\n    keeper.release();\n}\n\n'''
if old_helper not in s:
    raise SystemExit('reject helper marker not found')
s = s.replace(old_helper, '', 1)

old = '''    RootTaskKeeper rejectedAccept(client.rootTask());\n    rejectedFt->prepare();\n    check(waitFor([&]() { return rejectedAccept.task() != nullptr; }),\n          "rollback fixture did not serialize content-accept");\n    rejectJingleTask(rejectedAccept, peer);\n    QCoreApplication::processEvents(QEventLoop::AllEvents);\n\n    check(session.negotiatedGroupings().size() == 1\n              && session.negotiatedGroupings().first().contents\n                     == QStringList({ offer.audioName, offer.videoName, fileName })\n              && icePad->liveAssociationCount() == 1,\n          "failed content-accept changed established BUNDLE topology or lifetime");\n'''
new = '''    // Stage the second content on the existing association, then reject it\n    // locally before the queued ContentAccept can be serialized. Session must\n    // roll back only the provisional membership before sending ContentRemove.\n    rejectedFt->prepare();\n    auto rejectedTransport = qSharedPointerDynamicCast<J::ICE::Transport>(rejectedFt->transport());\n    check(bool(rejectedTransport), "rollback fixture did not create ICE transport");\n    bool rejectedBound = false, rejectedRequired = false;\n    auto *rejectedProvisional\n        = icePad->groupedConnectionFor(rejectedTransport.data(), &rejectedBound, &rejectedRequired);\n    check(rejectedBound && rejectedRequired && rejectedProvisional == shared\n              && icePad->liveAssociationCount() == 1,\n          "rollback fixture did not stage on the established BUNDLE association");\n\n    rejectedFt->remove(J::Reason::Decline, QStringLiteral("declined by local policy"));\n    check(waitFor([&]() {\n              const auto groups = session.negotiatedGroupings();\n              return groups.size() == 1\n                  && groups.first().contents\n                      == QStringList({ offer.audioName, offer.videoName, fileName })\n                  && icePad->liveAssociationCount() == 1;\n          }),\n          "local rejection changed established BUNDLE topology or lifetime");\n\n    bool rejectedStillBound = false, rejectedStillRequired = false;\n    check(icePad->groupedConnectionFor(rejectedTransport.data(), &rejectedStillBound, &rejectedStillRequired) == nullptr\n              && !rejectedStillBound && !rejectedStillRequired,\n          "local rejection retained provisional BUNDLE membership");\n'''
if old not in s:
    raise SystemExit('rollback block marker not found')
s = s.replace(old, new, 1)
p.write_text(s)
